### ISSUE TITLE
How can I add multiple FILTER RULES?

### ISSUE THREAD

**Issue by jaeseok-park** [mattijs/node-rsync#28]
I would like to rsync some directories from a server to local with --delete-after and --delete-excluded options.
To use --delete-excluded option, I need two filter rules.
According to the man page, "You may use as many --filter options on the command line as you like to build up the list of files to exclude."
However, I've failed to add two filter rules with set() function. Only the last filter option works.

I cannot use merge file due to the limitation of my filesystem. I can use only command-line filter rule.

Could you add the feature that multiple --filter options work?

**Comment by mattijs** [comment]
This is something that I really mis myself and that I have been working on for a while, but has been severely delayed. I don't know when I'll be able to finish it. Any PR's are welcome in the meantime :smile:
