### ISSUE TITLE
Can it be used on windows machines?

### ISSUE THREAD

**Issue by Jeff-Tian** [mattijs/node-rsync#29]
Can it be used on windows systems that don't support `rsync` natively?

**Comment by Nepoxx** [comment]
It would be great to document that on the main page.

https://www.npmjs.com/package/scp2 does so. I'll investigate the source if I get some time.

**Comment by mattijs** [comment]
I haven't tested the library on Windows but like @Nepoxx said it should work from a code perspective.
I have no knowledge on how to get rsync running on Windows but it looks like it requires CygWin

Any experiences in getting it running are welcome.

The properties `executable` and `executableShell` might change the behavior on Windows so you could fiddle around with those.

**Comment by born2net** [comment]
works great in Windows


```
gulp.task('rsync', function () {
    var rsync = Rsync.build({
        source: '/cygdrive/c/msweb/signagestudio_web-lite/',
        destination: 'user@example.com/var/www/sites/dynasite/htdocs/_studio-dev/',
        exclude: ['*.bat', '*.iml', '.gitignore', 'gulpfile.js', '.git', '.idea/', '_common/', '_doctheme/', '_assets/', '_utils/', '*node_modules', '*SignageStudio/', '*Spotify/']
    });
    rsync.set('progress');
    rsync.flags('avz');
    console.log('running the command ' + rsync.command());
    rsync.output(
        function (data) {
            console.log('sync: ' + data);
        }, function (data) {
            console.log('sync: ' + data);
        }
    );
    rsync.execute(function (error, stdout, stderr) {
        console.log('completed ' + error + ' ' + stdout + ' ' + stderr)
    });
});
``

**Comment by wanghaisheng** [comment]
@born2net  could you share your work about how to setup environment and deploy to windows server or windows system？
