### ISSUE TITLE
Rsync freeze after running task on gulp

### ISSUE THREAD

**Issue by heldrida** [mattijs/node-rsync#30]
When Rsync finishes running using gulp, the console get's freezed on the "Finished 'x' after 'x'ms ( [13:22:17] Finished 'sync' after 5.38 ms ), without getting back to allow me type in the command line;

This is what I have:

gulp.task('sync', function () {

	// Build the command
	var rsync = new Rsync()
		.flags('va')
		.source('./')
		.destination('../../xxx');

	// Execute the command
	rsync.execute(function(error, code, cmd) {
		console.log('Rsync is complete!');
	});

});

**Comment by Anarchid** [comment]
I'm having a similar issue when executing multiple rsyncs one after another. Adding an output handler via `.output` seems to be a workaround.

**Comment by mattijs** [comment]
I'm not a gulp expert but I believe you have to call `done` for async [gulp tasks](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulptaskname--deps-fn), for example:

```javascript
gulp.task(function (done) {
  var cmd = Rsync.build(options);

  cmd.execute(function (error, code, cmd) {
    done();
  });
});
```

Closing this because looks like a gulp issue.
