### ISSUE TITLE
Publish version with cwd

### ISSUE THREAD

**Issue by rumkin** [mattijs/node-rsync#39]
Please publish to npm version with cwd support.

**Comment by mattijs** [comment]
Hey @rumkin,

I'll try to release a version as soon as possible. In the mean time you can also point directly to this git repository from you `package.json` to get the latest version:

```javascript
"dependencies": {
  "node-rsync": "git://github.com/mattijs/node-rsync.git#master"
}
```
See https://docs.npmjs.com/files/package.json#dependencies for more details.

**Comment by mattijs** [comment]
A new version is up on npm with the latest changes: https://www.npmjs.com/package/rsync

Thank you again for you contributions :tada:
