### ISSUE TITLE
Escaping $ in *nix platforms

### ISSUE THREAD

**Issue by lekkas** [mattijs/node-rsync#40]
I noticed that `$` is not escaped as it probably should in Linux/OS X. For instance, this:

```javascript
Rsync = require('rsync')
var rsync = new Rsync()
  .flags('az')
  .source('/source')
  .destination('server:/destination$test')
  .command()
```

will yield

```javascript
"rsync -az /source server:/destination$test"
```

So when the rsync command is run, `$test` will be interpreted as an environment variable.

**Comment by mattijs** [comment]
I wanted to keep this as a feature but I'm starting to think that it doesn't make sense. Would you be willing to open a PR for this?

**Comment by lekkas** [comment]
Sure.
