### ISSUE TITLE
Reporting --stats?

### ISSUE THREAD

**Issue by lostthetrail** [mattijs/node-rsync#42]
Is there a known pattern for reporting the output of `--stats` from rsync back to one of the handlers?

**Comment by mattijs** [comment]
To get the output from `--stats` (or any stdout output) you can register an output handler through `output(stdoutHandler, stderrHandler)`. The handler receives a buffer with the output from stdout (or stderr):

```javascript
let command = new Rsync();
command.output(function (stdoutBuffer) {
  // Parse the buffer in here
});
```

See documentation in the README: https://github.com/mattijs/node-rsync#outputstdouthandler-stderrhandler

I haven't tried to parse the actual output for stats myself but I'm sure its doable.
